var F4InverseLookup = [
    {number: Field.F4Zero, inverse: Field.F4One},
    {number: Field.F4One, inverse: Field.F4One},
    {number: Field.F4Alpha, inverse: Field.F4AlphaPlusOne},
    {number: Field.F4AlphaPlusOne, inverse: Field.F4Alpha}
];

var F4AdditionLookup = [
    {summand1: Field.F4Zero, summand2: Field.F4Zero, result: Field.F4},
    {summand1: Field.F4Zero, summand2: Field.F4One, result: Field.F4},
    {summand1: Field.F4Zero, summand2: Field.F4Alpha, result: Field.F4},
    {summand1: Field.F4Zero, summand2: Field.F4AlphaPlusOne, result: Field.F4},
    {summand1: Field.F4One, summand2: Field.F4Zero, result: Field.F4},
    {summand1: Field.F4One, summand2: Field.F4One, result: Field.F4},
    {summand1: Field.F4One, summand2: Field.F4Alpha, result: Field.F4},
    {summand1: Field.F4One, summand2: Field.F4AlphaPlusOne, result: Field.F4},
    {summand1: Field.F4Alpha, summand2: Field.F4Zero, result: Field.F4},
    {summand1: Field.F4Alpha, summand2: Field.F4One, result: Field.F4},
    {summand1: Field.F4Alpha, summand2: Field.F4Alpha, result: Field.F4},
    {summand1: Field.F4Alpha, summand2: Field.F4AlphaPlusOne, result: Field.F4},
    {summand1: Field.F4AlphaPlusOne, summand2: Field.F4Zero, result: Field.F4},
    {summand1: Field.F4AlphaPlusOne, summand2: Field.F4One, result: Field.F4},
    {summand1: Field.F4AlphaPlusOne, summand2: Field.F4Alpha, result: Field.F4},
    {summand1: Field.F4AlphaPlusOne, summand2: Field.F4AlphaPlusOne, result: Field.F4}
];

var F4MultiplicationLookup = [
    {factor1: Field.F4Zero, factor2: Field.F4Zero, result: Field.F4},
    {factor1: Field.F4Zero, factor2: Field.F4One, result: Field.F4},
    {factor1: Field.F4Zero, factor2: Field.F4Alpha, result: Field.F4},
    {factor1: Field.F4Zero, factor2: Field.F4AlphaPlusOne, result: Field.F4},
    {factor1: Field.F4One, factor2: Field.F4Zero, result: Field.F4},
    {factor1: Field.F4One, factor2: Field.F4One, result: Field.F4},
    {factor1: Field.F4One, factor2: Field.F4Alpha, result: Field.F4},
    {factor1: Field.F4One, factor2: Field.F4AlphaPlusOne, result: Field.F4},
    {factor1: Field.F4Alpha, factor2: Field.F4Zero, result: Field.F4},
    {factor1: Field.F4Alpha, factor2: Field.F4One, result: Field.F4},
    {factor1: Field.F4Alpha, factor2: Field.F4Alpha, result: Field.F4},
    {factor1: Field.F4Alpha, factor2: Field.F4AlphaPlusOne, result: Field.F4},
    {factor1: Field.F4AlphaPlusOne, factor2: Field.F4Zero, result: Field.F4},
    {factor1: Field.F4AlphaPlusOne, factor2: Field.F4One, result: Field.F4},
    {factor1: Field.F4AlphaPlusOne, factor2: Field.F4Alpha, result: Field.F4},
    {factor1: Field.F4AlphaPlusOne, factor2: Field.F4AlphaPlusOne, result: Field.F4}
];

var F8InverseLookup = [
    {number: Field.F8Zero, inverse: Field.F8},
    {number: Field.F8One, inverse: Field.F8},
    {number: Field.F8Beta, inverse: Field.F8},
    {number: Field.F8OneplusBeta, inverse: Field.F8},
    {number: Field.F8BetaSquare, inverse: Field.F8},
    {number: Field.F8F8OnePlusBetaSquare, inverse: Field.F8},
    {number: Field.F8BetaPlusBetaSquare, inverse: Field.F8},
    {number: Field.F8OnePlusBetaPlusBetaSquare, inverse: Field.F8}
];

var F8AdditionTable = [
    {summand1: Field.F8Zero, summand2: Field.F8Zero, result: Field.F8},
    {summand1: Field.F8Zero, summand2: Field.F8One, result: Field.F8},
    {summand1: Field.F8Zero, summand2: Field.F8Beta, result: Field.F8},
    {summand1: Field.F8Zero, summand2: Field.F8OneplusBeta, result: Field.F8},
    {summand1: Field.F8Zero, summand2: Field.F8BetaSquare, result: Field.F8},
    {summand1: Field.F8Zero, summand2: Field.F8F8OnePlusBetaSquare, result: Field.F8},
    {summand1: Field.F8Zero, summand2: Field.F8BetaPlusBetaSquare, result: Field.F8},
    {summand1: Field.F8Zero, summand2: Field.F8OnePlusBetaPlusBetaSquare, result: Field.F8},
    {summand1: Field.F8One, summand2: Field.F8Zero, result: Field.F8},
    {summand1: Field.F8One, summand2: Field.F8One, result: Field.F8},
    {summand1: Field.F8One, summand2: Field.F8Beta, result: Field.F8},
    {summand1: Field.F8One, summand2: Field.F8OnePlusBeta, result: Field.F8},
    {summand1: Field.F8One, summand2: Field.F8BetaSquare, result: Field.F8},
    {summand1: Field.F8One, summand2: Field.F8OnePlusBetaSquare, result: Field.F8},
    {summand1: Field.F8One, summand2: Field.F8BetaPlusBetaSquare, result: Field.F8},
    {summand1: Field.F8One, summand2: Field.F8OnePlusBetaPlusBetaSquare, result: Field.F8},
    {summand1: Field.F8Beta, summand2: Field.F8Zero, result: Field.F8},
    {summand1: Field.F8Beta, summand2: Field.F8One, result: Field.F8},
    {summand1: Field.F8Beta, summand2: Field.F8Beta, result: Field.F8},
    {summand1: Field.F8Beta, summand2: Field.F8OnePlusBeta, result: Field.F8},
    {summand1: Field.F8Beta, summand2: Field.F8BetaSquare, result: Field.F8},
    {summand1: Field.F8Beta, summand2: Field.F8OnePlusBetaSquare, result: Field.F8},
    {summand1: Field.F8Beta, summand2: Field.F8BetaPlusBetaSquare, result: Field.F8},
    {summand1: Field.F8Beta, summand2: Field.F8OnePlusBetaPlusBetaSquare, result: Field.F8},
    {summand1: Field.F8OnePlusBeta, summand2: Field.F8Zero, result: Field.F8},
    {summand1: Field.F8OnePlusBeta, summand2: Field.F8One, result: Field.F8},
    {summand1: Field.F8OnePlusBeta, summand2: Field.F8Beta, result: Field.F8},
    {summand1: Field.F8OnePlusBeta, summand2: Field.F8OnePlusBeta, result: Field.F8},
    {summand1: Field.F8OnePlusBeta, summand2: Field.F8BetaSquare, result: Field.F8},
    {summand1: Field.F8OnePlusBeta, summand2: Field.F8OnePlusBetaSquare, result: Field.F8},
    {summand1: Field.F8OnePlusBeta, summand2: Field.F8BetaPlusBetaSquare, result: Field.F8},
    {summand1: Field.F8OnePlusBeta, summand2: Field.F8OnePlusBetaPlusBetaSquare, result: Field.F8},
    {summand1: Field.F8BetaSquare, summand2: Field.F8Zero, result: Field.F8},
    {summand1: Field.F8BetaSquare, summand2: Field.F8One, result: Field.F8},
    {summand1: Field.F8BetaSquare, summand2: Field.F8Beta, result: Field.F8},
    {summand1: Field.F8BetaSquare, summand2: Field.F8OnePlusBeta, result: Field.F8},
    {summand1: Field.F8BetaSquare, summand2: Field.F8BetaSquare, result: Field.F8},
    {summand1: Field.F8BetaSquare, summand2: Field.F8OnePlusBetaSquare, result: Field.F8},
    {summand1: Field.F8BetaSquare, summand2: Field.F8BetaPlusBetaSquare, result: Field.F8},
    {summand1: Field.F8BetaSquare, summand2: Field.F8OnePlusBetaPlusBetaSquare, result: Field.F8},
    {summand1: Field.F8OnePlusBetaSquare, summand2: Field.F8Zero, result: Field.F8},
    {summand1: Field.F8OnePlusBetaSquare, summand2: Field.F8One, result: Field.F8},
    {summand1: Field.F8OnePlusBetaSquare, summand2: Field.F8Beta, result: Field.F8},
    {summand1: Field.F8OnePlusBetaSquare, summand2: Field.F8OnePlusBeta, result: Field.F8},
    {summand1: Field.F8OnePlusBetaSquare, summand2: Field.F8BetaSquare, result: Field.F8},
    {summand1: Field.F8OnePlusBetaSquare, summand2: Field.F8OnePlusBetaSquare, result: Field.F8},
    {summand1: Field.F8OnePlusBetaSquare, summand2: Field.F8BetaPlusBetaSquare, result: Field.F8},
    {summand1: Field.F8OnePlusBetaSquare, summand2: Field.F8OnePlusBetaPlusBetaSquare, result: Field.F8},
    {summand1: Field.F8BetaPlusBetaSquare, summand2: Field.F8Zero, result: Field.F8},
    {summand1: Field.F8BetaPlusBetaSquare, summand2: Field.F8One, result: Field.F8},
    {summand1: Field.F8BetaPlusBetaSquare, summand2: Field.F8Beta, result: Field.F8},
    {summand1: Field.F8BetaPlusBetaSquare, summand2: Field.F8OnePlusBeta, result: Field.F8},
    {summand1: Field.F8BetaPlusBetaSquare, summand2: Field.F8BetaSquare, result: Field.F8},
    {summand1: Field.F8BetaPlusBetaSquare, summand2: Field.F8OnePlusBetaSquare, result: Field.F8},
    {summand1: Field.F8BetaPlusBetaSquare, summand2: Field.F8BetaPlusBetaSquare, result: Field.F8},
    {summand1: Field.F8BetaPlusBetaSquare, summand2: Field.F8OnePlusBetaPlusBetaSquare, result: Field.F8},
    {summand1: Field.F8OnePlusBetaPlusBetaSquare, summand2: Field.F8Zero, result: Field.F8},
    {summand1: Field.F8OnePlusBetaPlusBetaSquare, summand2: Field.F8One, result: Field.F8},
    {summand1: Field.F8OnePlusBetaPlusBetaSquare, summand2: Field.F8Beta, result: Field.F8},
    {summand1: Field.F8OnePlusBetaPlusBetaSquare, summand2: Field.F8OnePlusBeta, result: Field.F8},
    {summand1: Field.F8OnePlusBetaPlusBetaSquare, summand2: Field.F8BetaSquare, result: Field.F8},
    {summand1: Field.F8OnePlusBetaPlusBetaSquare, summand2: Field.F8OnePlusBetaSquare, result: Field.F8},
    {summand1: Field.F8OnePlusBetaPlusBetaSquare, summand2: Field.F8BetaPlusBetaSquare, result: Field.F8},
    {summand1: Field.F8OnePlusBetaPlusBetaSquare, summand2: Field.F8OnePlusBetaPlusBetaSquare, result: Field.F8}
];

var F8MultiplicationTable = [
    {factor1: Field.F8Zero, factor2: Field.F8Zero, result: Field.F8},
    {factor1: Field.F8Zero, factor2: Field.F8One, result: Field.F8},
    {factor1: Field.F8Zero, factor2: Field.F8Beta, result: Field.F8},
    {factor1: Field.F8Zero, factor2: Field.F8OneplusBeta, result: Field.F8},
    {factor1: Field.F8Zero, factor2: Field.F8BetaSquare, result: Field.F8},
    {factor1: Field.F8Zero, factor2: Field.F8F8OnePlusBetaSquare, result: Field.F8},
    {factor1: Field.F8Zero, factor2: Field.F8BetaPlusBetaSquare, result: Field.F8},
    {factor1: Field.F8Zero, factor2: Field.F8OnePlusBetaPlusBetaSquare, result: Field.F8},
    {factor1: Field.F8One, factor2: Field.F8Zero, result: Field.F8},
    {factor1: Field.F8One, factor2: Field.F8One, result: Field.F8},
    {factor1: Field.F8One, factor2: Field.F8Beta, result: Field.F8},
    {factor1: Field.F8One, factor2: Field.F8OnePlusBeta, result: Field.F8},
    {factor1: Field.F8One, factor2: Field.F8BetaSquare, result: Field.F8},
    {factor1: Field.F8One, factor2: Field.F8OnePlusBetaSquare, result: Field.F8},
    {factor1: Field.F8One, factor2: Field.F8BetaPlusBetaSquare, result: Field.F8},
    {factor1: Field.F8One, factor2: Field.F8OnePlusBetaPlusBetaSquare, result: Field.F8},
    {factor1: Field.F8Beta, factor2: Field.F8Zero, result: Field.F8},
    {factor1: Field.F8Beta, factor2: Field.F8One, result: Field.F8},
    {factor1: Field.F8Beta, factor2: Field.F8Beta, result: Field.F8},
    {factor1: Field.F8Beta, factor2: Field.F8OnePlusBeta, result: Field.F8},
    {factor1: Field.F8Beta, factor2: Field.F8BetaSquare, result: Field.F8},
    {factor1: Field.F8Beta, factor2: Field.F8OnePlusBetaSquare, result: Field.F8},
    {factor1: Field.F8Beta, factor2: Field.F8BetaPlusBetaSquare, result: Field.F8},
    {factor1: Field.F8Beta, factor2: Field.F8OnePlusBetaPlusBetaSquare, result: Field.F8},
    {factor1: Field.F8OnePlusBeta, factor2: Field.F8Zero, result: Field.F8},
    {factor1: Field.F8OnePlusBeta, factor2: Field.F8One, result: Field.F8},
    {factor1: Field.F8OnePlusBeta, factor2: Field.F8Beta, result: Field.F8},
    {factor1: Field.F8OnePlusBeta, factor2: Field.F8OnePlusBeta, result: Field.F8},
    {factor1: Field.F8OnePlusBeta, factor2: Field.F8BetaSquare, result: Field.F8},
    {factor1: Field.F8OnePlusBeta, factor2: Field.F8OnePlusBetaSquare, result: Field.F8},
    {factor1: Field.F8OnePlusBeta, factor2: Field.F8BetaPlusBetaSquare, result: Field.F8},
    {factor1: Field.F8OnePlusBeta, factor2: Field.F8OnePlusBetaPlusBetaSquare, result: Field.F8},
    {factor1: Field.F8BetaSquare, factor2: Field.F8Zero, result: Field.F8},
    {factor1: Field.F8BetaSquare, factor2: Field.F8One, result: Field.F8},
    {factor1: Field.F8BetaSquare, factor2: Field.F8Beta, result: Field.F8},
    {factor1: Field.F8BetaSquare, factor2: Field.F8OnePlusBeta, result: Field.F8},
    {factor1: Field.F8BetaSquare, factor2: Field.F8BetaSquare, result: Field.F8},
    {factor1: Field.F8BetaSquare, factor2: Field.F8OnePlusBetaSquare, result: Field.F8},
    {factor1: Field.F8BetaSquare, factor2: Field.F8BetaPlusBetaSquare, result: Field.F8},
    {factor1: Field.F8BetaSquare, factor2: Field.F8OnePlusBetaPlusBetaSquare, result: Field.F8},
    {factor1: Field.F8OnePlusBetaSquare, factor2: Field.F8Zero, result: Field.F8},
    {factor1: Field.F8OnePlusBetaSquare, factor2: Field.F8One, result: Field.F8},
    {factor1: Field.F8OnePlusBetaSquare, factor2: Field.F8Beta, result: Field.F8},
    {factor1: Field.F8OnePlusBetaSquare, factor2: Field.F8OnePlusBeta, result: Field.F8},
    {factor1: Field.F8OnePlusBetaSquare, factor2: Field.F8BetaSquare, result: Field.F8},
    {factor1: Field.F8OnePlusBetaSquare, factor2: Field.F8OnePlusBetaSquare, result: Field.F8},
    {factor1: Field.F8OnePlusBetaSquare, factor2: Field.F8BetaPlusBetaSquare, result: Field.F8},
    {factor1: Field.F8OnePlusBetaSquare, factor2: Field.F8OnePlusBetaPlusBetaSquare, result: Field.F8},
    {factor1: Field.F8BetaPlusBetaSquare, factor2: Field.F8Zero, result: Field.F8},
    {factor1: Field.F8BetaPlusBetaSquare, factor2: Field.F8One, result: Field.F8},
    {factor1: Field.F8BetaPlusBetaSquare, factor2: Field.F8Beta, result: Field.F8},
    {factor1: Field.F8BetaPlusBetaSquare, factor2: Field.F8OnePlusBeta, result: Field.F8},
    {factor1: Field.F8BetaPlusBetaSquare, factor2: Field.F8BetaSquare, result: Field.F8},
    {factor1: Field.F8BetaPlusBetaSquare, factor2: Field.F8OnePlusBetaSquare, result: Field.F8},
    {factor1: Field.F8BetaPlusBetaSquare, factor2: Field.F8BetaPlusBetaSquare, result: Field.F8},
    {factor1: Field.F8BetaPlusBetaSquare, factor2: Field.F8OnePlusBetaPlusBetaSquare, result: Field.F8},
    {factor1: Field.F8OnePlusBetaPlusBetaSquare, factor2: Field.F8Zero, result: Field.F8},
    {factor1: Field.F8OnePlusBetaPlusBetaSquare, factor2: Field.F8One, result: Field.F8},
    {factor1: Field.F8OnePlusBetaPlusBetaSquare, factor2: Field.F8Beta, result: Field.F8},
    {factor1: Field.F8OnePlusBetaPlusBetaSquare, factor2: Field.F8OnePlusBeta, result: Field.F8},
    {factor1: Field.F8OnePlusBetaPlusBetaSquare, factor2: Field.F8BetaSquare, result: Field.F8},
    {factor1: Field.F8OnePlusBetaPlusBetaSquare, factor2: Field.F8OnePlusBetaSquare, result: Field.F8},
    {factor1: Field.F8OnePlusBetaPlusBetaSquare, factor2: Field.F8BetaPlusBetaSquare, result: Field.F8},
    {factor1: Field.F8OnePlusBetaPlusBetaSquare, factor2: Field.F8OnePlusBetaPlusBetaSquare, result: Field.F8}
];

var F9InverseLookup = [
    {number: Field.F9Zero, inverse: Field.F9},
    {number: Field.F9One, inverse: Field.F9},
    {number: Field.F9MinusOne, inverse: Field.F9},
    {number: Field.F9Iota, inverse: Field.F9},
    {number: Field.F9IotaPlusOne, inverse: Field.F9},
    {number: Field.F9IotaMinusOne, inverse: Field.F9},
    {number: Field.F9MinusIota, inverse: Field.F9},
    {number: Field.F9MinusIotaPlusOne, inverse: Field.F9},
    {number: Field.F9MinusIotaMinusOne, inverse: Field.F9},
];

var F9AdditionTable = [
    {summand1: Field.F9Zero, summand2: Field.F9Zero, result: Field.F9},
    {summand1: Field.F9Zero, summand2: Field.F9One, result: Field.F9},
    {summand1: Field.F9Zero, summand2: Field.F9MinusOne, result: Field.F9},
    {summand1: Field.F9Zero, summand2: Field.F9Iota, result: Field.F9},
    {summand1: Field.F9Zero, summand2: Field.F9IotaPlusOne, result: Field.F9},
    {summand1: Field.F9Zero, summand2: Field.F9IotaMinusOne, result: Field.F9},
    {summand1: Field.F9Zero, summand2: Field.F9MinusIota, result: Field.F9},
    {summand1: Field.F9Zero, summand2: Field.F9MinusIotaPlusOne, result: Field.F9},
    {summand1: Field.F9Zero, summand2: Field.F9MinusIotaMinusOne, result: Field.F9},
    {summand1: Field.F9One, summand2: Field.F9Zero, result: Field.F9},
    {summand1: Field.F9One, summand2: Field.F9One, result: Field.F9},
    {summand1: Field.F9One, summand2: Field.F9MinusOne, result: Field.F9},
    {summand1: Field.F9One, summand2: Field.F9Iota, result: Field.F9},
    {summand1: Field.F9One, summand2: Field.F9IotaPlusOne, result: Field.F9},
    {summand1: Field.F9One, summand2: Field.F9IotaMinusOne, result: Field.F9},
    {summand1: Field.F9One, summand2: Field.F9MinusIota, result: Field.F9},
    {summand1: Field.F9One, summand2: Field.F9MinusIotaPlusOne, result: Field.F9},
    {summand1: Field.F9One, summand2: Field.F9MinusIotaMinusOne, result: Field.F9},
    {summand1: Field.F9MinusOne, summand2: Field.F9Zero, result: Field.F9},
    {summand1: Field.F9MinusOne, summand2: Field.F9One, result: Field.F9},
    {summand1: Field.F9MinusOne, summand2: Field.F9MinusOne, result: Field.F9},
    {summand1: Field.F9MinusOne, summand2: Field.F9Iota, result: Field.F9},
    {summand1: Field.F9MinusOne, summand2: Field.F9IotaPlusOne, result: Field.F9},
    {summand1: Field.F9MinusOne, summand2: Field.F9IotaMinusOne, result: Field.F9},
    {summand1: Field.F9MinusOne, summand2: Field.F9MinusIota, result: Field.F9},
    {summand1: Field.F9MinusOne, summand2: Field.F9MinusIotaPlusOne, result: Field.F9},
    {summand1: Field.F9MinusOne, summand2: Field.F9MinusIotaMinusOne, result: Field.F9},
    {summand1: Field.F9Iota, summand2: Field.F9Zero, result: Field.F9},
    {summand1: Field.F9Iota, summand2: Field.F9One, result: Field.F9},
    {summand1: Field.F9Iota, summand2: Field.F9MinusOne, result: Field.F9},
    {summand1: Field.F9Iota, summand2: Field.F9Iota, result: Field.F9},
    {summand1: Field.F9Iota, summand2: Field.F9IotaPlusOne, result: Field.F9},
    {summand1: Field.F9Iota, summand2: Field.F9IotaMinusOne, result: Field.F9},
    {summand1: Field.F9Iota, summand2: Field.F9MinusIota, result: Field.F9},
    {summand1: Field.F9Iota, summand2: Field.F9MinusIotaPlusOne, result: Field.F9},
    {summand1: Field.F9Iota, summand2: Field.F9MinusIotaMinusOne, result: Field.F9},
    {summand1: Field.F9IotaPlusOne, summand2: Field.F9Zero, result: Field.F9},
    {summand1: Field.F9IotaPlusOne, summand2: Field.F9One, result: Field.F9},
    {summand1: Field.F9IotaPlusOne, summand2: Field.F9MinusOne, result: Field.F9},
    {summand1: Field.F9IotaPlusOne, summand2: Field.F9Iota, result: Field.F9},
    {summand1: Field.F9IotaPlusOne, summand2: Field.F9IotaPlusOne, result: Field.F9},
    {summand1: Field.F9IotaPlusOne, summand2: Field.F9IotaMinusOne, result: Field.F9},
    {summand1: Field.F9IotaPlusOne, summand2: Field.F9MinusIota, result: Field.F9},
    {summand1: Field.F9IotaPlusOne, summand2: Field.F9MinusIotaPlusOne, result: Field.F9},
    {summand1: Field.F9IotaPlusOne, summand2: Field.F9MinusIotaMinusOne, result: Field.F9},
    {summand1: Field.F9IotaMinusOne, summand2: Field.F9Zero, result: Field.F9},
    {summand1: Field.F9IotaMinusOne, summand2: Field.F9One, result: Field.F9},
    {summand1: Field.F9IotaMinusOne, summand2: Field.F9MinusOne, result: Field.F9},
    {summand1: Field.F9IotaMinusOne, summand2: Field.F9Iota, result: Field.F9},
    {summand1: Field.F9IotaMinusOne, summand2: Field.F9IotaPlusOne, result: Field.F9},
    {summand1: Field.F9IotaMinusOne, summand2: Field.F9IotaMinusOne, result: Field.F9},
    {summand1: Field.F9IotaMinusOne, summand2: Field.F9MinusIota, result: Field.F9},
    {summand1: Field.F9IotaMinusOne, summand2: Field.F9MinusIotaPlusOne, result: Field.F9},
    {summand1: Field.F9IotaMinusOne, summand2: Field.F9MinusIotaMinusOne, result: Field.F9},
    {summand1: Field.F9MinusIota, summand2: Field.F9Zero, result: Field.F9},
    {summand1: Field.F9MinusIota, summand2: Field.F9One, result: Field.F9},
    {summand1: Field.F9MinusIota, summand2: Field.F9MinusOne, result: Field.F9},
    {summand1: Field.F9MinusIota, summand2: Field.F9Iota, result: Field.F9},
    {summand1: Field.F9MinusIota, summand2: Field.F9IotaPlusOne, result: Field.F9},
    {summand1: Field.F9MinusIota, summand2: Field.F9IotaMinusOne, result: Field.F9},
    {summand1: Field.F9MinusIota, summand2: Field.F9MinusIota, result: Field.F9},
    {summand1: Field.F9MinusIota, summand2: Field.F9MinusIotaPlusOne, result: Field.F9},
    {summand1: Field.F9MinusIota, summand2: Field.F9MinusIotaMinusOne, result: Field.F9},
    {summand1: Field.F9MinusIotaPlusOne, summand2: Field.F9Zero, result: Field.F9},
    {summand1: Field.F9MinusIotaPlusOne, summand2: Field.F9One, result: Field.F9},
    {summand1: Field.F9MinusIotaPlusOne, summand2: Field.F9MinusOne, result: Field.F9},
    {summand1: Field.F9MinusIotaPlusOne, summand2: Field.F9Iota, result: Field.F9},
    {summand1: Field.F9MinusIotaPlusOne, summand2: Field.F9IotaPlusOne, result: Field.F9},
    {summand1: Field.F9MinusIotaPlusOne, summand2: Field.F9IotaMinusOne, result: Field.F9},
    {summand1: Field.F9MinusIotaPlusOne, summand2: Field.F9MinusIota, result: Field.F9},
    {summand1: Field.F9MinusIotaPlusOne, summand2: Field.F9MinusIotaPlusOne, result: Field.F9},
    {summand1: Field.F9MinusIotaPlusOne, summand2: Field.F9MinusIotaMinusOne, result: Field.F9},
    {summand1: Field.F9MinusIotaMinusOne, summand2: Field.F9Zero, result: Field.F9},
    {summand1: Field.F9MinusIotaMinusOne, summand2: Field.F9One, result: Field.F9},
    {summand1: Field.F9MinusIotaMinusOne, summand2: Field.F9MinusOne, result: Field.F9},
    {summand1: Field.F9MinusIotaMinusOne, summand2: Field.F9Iota, result: Field.F9},
    {summand1: Field.F9MinusIotaMinusOne, summand2: Field.F9IotaPlusOne, result: Field.F9},
    {summand1: Field.F9MinusIotaMinusOne, summand2: Field.F9IotaMinusOne, result: Field.F9},
    {summand1: Field.F9MinusIotaMinusOne, summand2: Field.F9MinusIota, result: Field.F9},
    {summand1: Field.F9MinusIotaMinusOne, summand2: Field.F9MinusIotaPlusOne, result: Field.F9},
    {summand1: Field.F9MinusIotaMinusOne, summand2: Field.F9MinusIotaMinusOne, result: Field.F9},
];

var F9MultiplicationTable = [
    {factor1: Field.F9Zero, factor2: Field.F9Zero, result: Field.F9},
    {factor1: Field.F9Zero, factor2: Field.F9One, result: Field.F9},
    {factor1: Field.F9Zero, factor2: Field.F9MinusOne, result: Field.F9},
    {factor1: Field.F9Zero, factor2: Field.F9Iota, result: Field.F9},
    {factor1: Field.F9Zero, factor2: Field.F9IotaPlusOne, result: Field.F9},
    {factor1: Field.F9Zero, factor2: Field.F9IotaMinusOne, result: Field.F9},
    {factor1: Field.F9Zero, factor2: Field.F9MinusIota, result: Field.F9},
    {factor1: Field.F9Zero, factor2: Field.F9MinusIotaPlusOne, result: Field.F9},
    {factor1: Field.F9Zero, factor2: Field.F9MinusIotaMinusOne, result: Field.F9},
    {factor1: Field.F9One, factor2: Field.F9Zero, result: Field.F9},
    {factor1: Field.F9One, factor2: Field.F9One, result: Field.F9},
    {factor1: Field.F9One, factor2: Field.F9MinusOne, result: Field.F9},
    {factor1: Field.F9One, factor2: Field.F9Iota, result: Field.F9},
    {factor1: Field.F9One, factor2: Field.F9IotaPlusOne, result: Field.F9},
    {factor1: Field.F9One, factor2: Field.F9IotaMinusOne, result: Field.F9},
    {factor1: Field.F9One, factor2: Field.F9MinusIota, result: Field.F9},
    {factor1: Field.F9One, factor2: Field.F9MinusIotaPlusOne, result: Field.F9},
    {factor1: Field.F9One, factor2: Field.F9MinusIotaMinusOne, result: Field.F9},
    {factor1: Field.F9MinusOne, factor2: Field.F9Zero, result: Field.F9},
    {factor1: Field.F9MinusOne, factor2: Field.F9One, result: Field.F9},
    {factor1: Field.F9MinusOne, factor2: Field.F9MinusOne, result: Field.F9},
    {factor1: Field.F9MinusOne, factor2: Field.F9Iota, result: Field.F9},
    {factor1: Field.F9MinusOne, factor2: Field.F9IotaPlusOne, result: Field.F9},
    {factor1: Field.F9MinusOne, factor2: Field.F9IotaMinusOne, result: Field.F9},
    {factor1: Field.F9MinusOne, factor2: Field.F9MinusIota, result: Field.F9},
    {factor1: Field.F9MinusOne, factor2: Field.F9MinusIotaPlusOne, result: Field.F9},
    {factor1: Field.F9MinusOne, factor2: Field.F9MinusIotaMinusOne, result: Field.F9},
    {factor1: Field.F9Iota, factor2: Field.F9Zero, result: Field.F9},
    {factor1: Field.F9Iota, factor2: Field.F9One, result: Field.F9},
    {factor1: Field.F9Iota, factor2: Field.F9MinusOne, result: Field.F9},
    {factor1: Field.F9Iota, factor2: Field.F9Iota, result: Field.F9},
    {factor1: Field.F9Iota, factor2: Field.F9IotaPlusOne, result: Field.F9},
    {factor1: Field.F9Iota, factor2: Field.F9IotaMinusOne, result: Field.F9},
    {factor1: Field.F9Iota, factor2: Field.F9MinusIota, result: Field.F9},
    {factor1: Field.F9Iota, factor2: Field.F9MinusIotaPlusOne, result: Field.F9},
    {factor1: Field.F9Iota, factor2: Field.F9MinusIotaMinusOne, result: Field.F9},
    {factor1: Field.F9IotaPlusOne, factor2: Field.F9Zero, result: Field.F9},
    {factor1: Field.F9IotaPlusOne, factor2: Field.F9One, result: Field.F9},
    {factor1: Field.F9IotaPlusOne, factor2: Field.F9MinusOne, result: Field.F9},
    {factor1: Field.F9IotaPlusOne, factor2: Field.F9Iota, result: Field.F9},
    {factor1: Field.F9IotaPlusOne, factor2: Field.F9IotaPlusOne, result: Field.F9},
    {factor1: Field.F9IotaPlusOne, factor2: Field.F9IotaMinusOne, result: Field.F9},
    {factor1: Field.F9IotaPlusOne, factor2: Field.F9MinusIota, result: Field.F9},
    {factor1: Field.F9IotaPlusOne, factor2: Field.F9MinusIotaPlusOne, result: Field.F9},
    {factor1: Field.F9IotaPlusOne, factor2: Field.F9MinusIotaMinusOne, result: Field.F9},
    {factor1: Field.F9IotaMinusOne, factor2: Field.F9Zero, result: Field.F9},
    {factor1: Field.F9IotaMinusOne, factor2: Field.F9One, result: Field.F9},
    {factor1: Field.F9IotaMinusOne, factor2: Field.F9MinusOne, result: Field.F9},
    {factor1: Field.F9IotaMinusOne, factor2: Field.F9Iota, result: Field.F9},
    {factor1: Field.F9IotaMinusOne, factor2: Field.F9IotaPlusOne, result: Field.F9},
    {factor1: Field.F9IotaMinusOne, factor2: Field.F9IotaMinusOne, result: Field.F9},
    {factor1: Field.F9IotaMinusOne, factor2: Field.F9MinusIota, result: Field.F9},
    {factor1: Field.F9IotaMinusOne, factor2: Field.F9MinusIotaPlusOne, result: Field.F9},
    {factor1: Field.F9IotaMinusOne, factor2: Field.F9MinusIotaMinusOne, result: Field.F9},
    {factor1: Field.F9MinusIota, factor2: Field.F9Zero, result: Field.F9},
    {factor1: Field.F9MinusIota, factor2: Field.F9One, result: Field.F9},
    {factor1: Field.F9MinusIota, factor2: Field.F9MinusOne, result: Field.F9},
    {factor1: Field.F9MinusIota, factor2: Field.F9Iota, result: Field.F9},
    {factor1: Field.F9MinusIota, factor2: Field.F9IotaPlusOne, result: Field.F9},
    {factor1: Field.F9MinusIota, factor2: Field.F9IotaMinusOne, result: Field.F9},
    {factor1: Field.F9MinusIota, factor2: Field.F9MinusIota, result: Field.F9},
    {factor1: Field.F9MinusIota, factor2: Field.F9MinusIotaPlusOne, result: Field.F9},
    {factor1: Field.F9MinusIota, factor2: Field.F9MinusIotaMinusOne, result: Field.F9},
    {factor1: Field.F9MinusIotaPlusOne, factor2: Field.F9Zero, result: Field.F9},
    {factor1: Field.F9MinusIotaPlusOne, factor2: Field.F9One, result: Field.F9},
    {factor1: Field.F9MinusIotaPlusOne, factor2: Field.F9MinusOne, result: Field.F9},
    {factor1: Field.F9MinusIotaPlusOne, factor2: Field.F9Iota, result: Field.F9},
    {factor1: Field.F9MinusIotaPlusOne, factor2: Field.F9IotaPlusOne, result: Field.F9},
    {factor1: Field.F9MinusIotaPlusOne, factor2: Field.F9IotaMinusOne, result: Field.F9},
    {factor1: Field.F9MinusIotaPlusOne, factor2: Field.F9MinusIota, result: Field.F9},
    {factor1: Field.F9MinusIotaPlusOne, factor2: Field.F9MinusIotaPlusOne, result: Field.F9},
    {factor1: Field.F9MinusIotaPlusOne, factor2: Field.F9MinusIotaMinusOne, result: Field.F9},
    {factor1: Field.F9MinusIotaMinusOne, factor2: Field.F9Zero, result: Field.F9},
    {factor1: Field.F9MinusIotaMinusOne, factor2: Field.F9One, result: Field.F9},
    {factor1: Field.F9MinusIotaMinusOne, factor2: Field.F9MinusOne, result: Field.F9},
    {factor1: Field.F9MinusIotaMinusOne, factor2: Field.F9Iota, result: Field.F9},
    {factor1: Field.F9MinusIotaMinusOne, factor2: Field.F9IotaPlusOne, result: Field.F9},
    {factor1: Field.F9MinusIotaMinusOne, factor2: Field.F9IotaMinusOne, result: Field.F9},
    {factor1: Field.F9MinusIotaMinusOne, factor2: Field.F9MinusIota, result: Field.F9},
    {factor1: Field.F9MinusIotaMinusOne, factor2: Field.F9MinusIotaPlusOne, result: Field.F9},
    {factor1: Field.F9MinusIotaMinusOne, factor2: Field.F9MinusIotaMinusOne, result: Field.F9},
];
